services:
  mixpost:
    image: inovector/mixpost-pro-team:latest
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage/app
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123! # Choose a secure root password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'mysql:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pRootPass123!"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped  

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  storage:
    driver: local
